site_name: Institut Sa Palomera - Base de Dades
site_description: Tutorial de com fer servir MkDocs i material

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo_vector_sapalomera_white.svg
  favicon: assets/logo_vector_sapalomera_gray.svg
  features:
    - navivatgion.top
    - navigation.tabs
    - navigation.sections # Serveis per tenir les seccions dins del sidebar
    - navigation.path
    - navigation.footer
    - navigation.instant # serveix per fer el teu site XHR sense recarregar tota la pàgina (serveix per sites grans)
    - toc.integrate
#    - header.autohide # Serveix per autoamagar el header s'amaga
    - search.suggest
    - search.highlight
    - conent.tabs.link
    - content.code.annotation
    - content.code.copy
  languace: ca
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: blue
      #accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: blue
      #accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode      

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to system preference
  font:
    text: Montserrat
    code: Montserrat Mono
  icon:
    admonition:
      note: octicons/tag-16
      success: octicons/check-16
nav:
  - index.md
  - Seeció1: folder1/index.md
  - Page 1: folder1/pag3.md
  - Page 2: folder1/page32.md      
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true   
extra_css:
  - assets/stylesheets/extra.css
extra:
  generator: true
#  consent:
#    cookies:
#      analytics:
#        name: Google Analytics
#        checked: true
#      github:
#        name: GitHub
#        checked: true        
#    actions:
#      - accept
#      - manage
  alternate:
    - name: Español
      link: /es/ 
      lang: es
    - name: English
      link: /en/ 
      lang: en

  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/robertventura
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/robertventura
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/robertventura
copyright: |
  &copy; 2023 <a haref="https://github.com/robertventura" target="_blank" rel="noopener">Robert Ventura</a>


